#!/bin/bash
set -euo pipefail

echo "Running osparc-opencore solver ..." > $LOG_FILE
pushd /home/opencor
/usr/local/bin/entrypoint.sh $STIMULATION_MODE $STIMULATION_LEVEL\
        > $OUTPUT_FOLDER/output.json \
        2>>$LOG_FILE
popd

