#!/bin/bash
cd $(dirname $0)
# ----------------------------------------------------------------
# This script shall be modified according to the needs in order to run the service
# The inputs defined in docker/inputs.json are available as env variables by their key in capital letters
# For example: input_1 -> $INPUT_1
# call stack:
# run -> do_run -> execute

set -e
echo "Starting solver" >> $LOG_FILE

cd /home/opencor
/usr/local/bin/entrypoint.sh $STIMULATION_PERIOD >> $OUTPUT_FOLDER/membrain-potential.json

echo "Done " >> $LOG_FILE

# then retrieve the output and move it to the $OUTPUT_FOLDER
# as defined in the output labels
# For example: cp output.csv $OUTPUT_FOLDER or to $OUTPUT_FOLDER/output.json using jq
#TODO: Replace following
#cat > $OUTPUT_FOLDER/output.json << EOF
##{
#
#    "output_1":"some_stuff"
#
#}
#EOF

