#!/bin/bash
set -e

echo "Starting osparc-opencore ..." > $LOG_FILE

cd /home/opencor
exec /usr/local/bin/entrypoint.sh $STIMULATION_PERIOD \
        > $OUTPUT_FOLDER/membrain-potential.json \
        2>>$LOG_FILE

echo "Finished osparc-opencore" >> $LOG_FILE
