#!/bin/bash
set -euo pipefail

echo "Converting json results to csv ..." >> $LOG_FILE
pushd $OUTPUT_FOLDER
# Assumes output
#   {
#    "heart_rate": 73,
#    "membrane": {
#        "v": [-47.78, -47.82, -47.85, ...]
#    }
#

echo "membrane-potential" > membrane-potential.csv
cat output.json | jq -r '.membrane.v[]' >> membrane-potential.csv

popd
