#!/bin/bash
set -euo pipefail

echo "Converting json results to csv ..." >> $LOG_FILE
pushd $OUTPUT_FOLDER
# Assumes output
#   {
#    "heart_rate": 73,
#    "membrane": {
#        "v": [-47.78, -47.82, -47.85, ...]
#    }
#
echo "index,transmembrane-potential [mV]" > membrane-potential.csv
VALUES="$(cat results.json | jq -r '.membrane.v[]')"
ENUMERATE=$(seq $(echo "${VALUES}" | wc -l))
paste -d",  "  <(echo "${ENUMERATE}") <(echo "${VALUES}") >> membrane-potential.csv
popd
